-- Create website_visitors table for telemetry
create table if not exists public.website_visitors (
  user_id uuid primary key,
  name text,
  email text,
  subscription text,
  event_type text,
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  visit_count int
);

-- Enable RLS and add permissive policies for anon usage (for demo/dev only)
-- For production, tighten these policies.
alter table public.website_visitors enable row level security;

create policy "allow_anon_insert" on public.website_visitors
  for insert with check (true);

create policy "allow_anon_select" on public.website_visitors
  for select using (true);

-- Optionally allow updates by anyone for merging duplicates (used by upsert)
create policy "allow_anon_update" on public.website_visitors
  for update using (true) with check (true);

-- Per-visit event log used by the Total Visits screen so each visit keeps its own timestamp.
create table if not exists public.website_visit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text,
  email text,
  subscription text,
  event_type text,
  seen_at timestamptz not null default now()
);

alter table public.website_visit_events enable row level security;

create policy "allow_anon_visit_event_insert" on public.website_visit_events
  for insert with check (true);

create policy "allow_anon_visit_event_select" on public.website_visit_events
  for select using (true);
