-- Create support_contributions table for direct UPI support tracking
create table if not exists public.support_contributions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id text,
  name text,
  email text,
  amount numeric(10,2) not null,
  currency text not null default 'INR',
  upi_id text not null,
  payee_name text,
  platform text,
  source text,
  payment_link text,
  status text not null default 'unverified'
);

alter table public.support_contributions enable row level security;

create policy "allow_anon_support_insert" on public.support_contributions
  for insert with check (true);

create policy "allow_anon_support_select" on public.support_contributions
  for select using (true);